server:
  build: .
  restart: always
  ports:
    - 80:80
    - 443:443
    - 53:53/udp
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - .:/app
  environment:
    - BALANCER_IP=192.168.99.100
